In [3]:
nums = [1,2,3,4,5,6,7,7]
unique = set(nums)
print(nums)
print(unique)

[1, 2, 3, 4, 5, 6, 7, 7]
{1, 2, 3, 4, 5, 6, 7}


In [4]:
for n in nums:
#loops
 if n%2 == 0:
   print('even')
 else:
   print('odd')

odd
even
odd
even
odd
even
odd
odd


In [5]:
for i in range(1,6):
  print(i)
while n>0:
  n-=1

1
2
3
4
5


In [6]:
#string reverse
s = 'python'
print(s[::-1])#slicing

nohtyp


In [7]:
#without slicing
s = input()
rev = ''
for ch in s:
  rev = ch + rev
print(rev)

In [8]:
#palindrome
s = input()
if s == s[::-1]:
  print('palindrome')
else:
  print('not palindrome')

palindrome


In [9]:
#without slicing
if rev == s:
  print('palindrome')
else:
  print('not palindrome')

palindrome


In [10]:
#lists
arr = [1,3,2,4,5,4]
print(max(arr))
print(min(arr))
print(sum(arr))

5
1
19


In [11]:
#unique
unique = list(set(arr))
print(unique)


[1, 2, 3, 4, 5]


In [12]:
#unique but without using set
unique = []
for i in arr:
  if i not in unique:
    unique.append(i)
print(unique)

[1, 3, 2, 4, 5]


In [13]:
#unique using dictionary
arr1 = [1,2,2,3,4,5,6,7,7,5,6,4,3,2]
freq = {}
for i in arr1:
  if i not in freq:
    freq[i] = 1
print(list(freq.keys()))

[1, 2, 3, 4, 5, 6, 7]


In [14]:
#list reverse
arr3 = [1,2,3,4,5]
arr3.reverse()
print(arr3)

[5, 4, 3, 2, 1]


In [15]:
#comprehensions
squares = [i*i for i in range(1, 6)]
even = [i for i in range(10) if i % 2 == 0]
dict_sq = {i: i*i for i in range(5)}
print(squares)
print(even)
print(dict_sq)

[1, 4, 9, 16, 25]
[0, 2, 4, 6, 8]
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


In [16]:
#move zeroes to the end
l1 =[1,2,0,0,0,0,9,0,8,0,333,0,9]
count = l1.count(0)
l1 = [x for x in l1 if x != 0 ] + count *[0]
print(l1)

[1, 2, 9, 8, 333, 9, 0, 0, 0, 0, 0, 0, 0]


In [17]:
#dictionary basics
student = {
    "name": "Musaib",
    "age": 21,
    "course": "CSE"
}
print(student['name'])      #access values
print(student['age'])
print(student['course'])

student.get("age")

student["city"] = "Srinagar"   # add
student["age"] = 22            # update

del student["city"]           # delete
print(student)

#student.pop("course")
#del student["age"]
#print(student)

print(student.keys())  # all keys
print(student.values())    # all values
student.items()     # (key, value) pairs


for k in student:
    print(k, student[k])

# or
for k, v in student.items():
    print(k, v)



Musaib
21
CSE
{'name': 'Musaib', 'age': 22, 'course': 'CSE'}
dict_keys(['name', 'age', 'course'])
dict_values(['Musaib', 22, 'CSE'])
name Musaib
age 22
course CSE
name Musaib
age 22
course CSE


In [18]:
#functions
def Is_even_odd(n):
  if n % 2 == 0:
    print('even')
  else:
    print('odd')
x = int(input)
Is_even_odd(x)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'method'

In [ ]:
def fact(n):
  fact = 1
  for i in range(1,n+1):
    fact = fact * i
  return fact
x = int(input())
print(fact(x))

4
24


In [ ]:
def Is_prime(n):
  Is_prime = True
  if n<= 1:
   Is_prime = False
  else:
    for i in range(2,int(n**0.5)+1):
      if n%i == 0:
        Is_prime = False
        break
  return Is_prime
x = int(input())
Is_prime(x)

3


True

In [ ]:
nums1 = [2,7,11,15,23,5,4,33,12]
target = int(input())
def two_sum(nums):
  seen = {}
  for i , num in enumerate(nums):
    if target-num in seen:
      return [seen[target - num],i]
    seen[num] = i
two_sum(nums1)

9


[0, 1]

In [ ]:
#vector operations
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*2)
print(np.dot(a,b))
print(a.shape)

[5 7 9]
[2 4 6]
32
(3,)


In [ ]:
#matrix operations
A = np.array([[2,3],[4,1]])
B = np.array([[5,6],[7,8]])

print(A+B)
print(np.dot(A,B))
print(A.shape)
print(A.T)

[[ 7  9]
 [11  9]]
[[31 36]
 [27 32]]
(2, 2)
[[2 4]
 [3 1]]
